set encoding=utf-8
set nocompatible	" required for Vundle
filetype off		" required for Vundle
syntax on		" display syntax highlighting

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

""" Plugins
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/syntastic'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'sheerun/vim-polyglot'

" all plugins must be before this line
call vundle#end()		" required for Vundle
filetype plugin indent on	" required for Vundle

" show line numbers
set number

" set colorscheme
colorscheme solarized

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" set shortcut for nerdtree
map <C-n> :NERDTreeToggle<CR>
" get rid of ^G before folders
let g:NERDTreeNodeDelimiter = "\u00a0"
" open nerdtree automatically if a directory was opened
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() ==1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" airline theme
let g:airline_theme='deus'
" use powerline fonts
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
